### ISSUE TITLE
Bug: Fresh install - admin command user not able to create

### ISSUE THREAD

**Issue by robajr** [cmintey/wishlist#191]
Fresh install, creating admin user

Website shows User with username or email already exists.

Docker log reports:

prisma:error 
Invalid `prisma.user.create()` invocation:
The column `hashedPassword` does not exist in the current database.

**Comment by robajr** [comment]
Other (related) log outputs prior to creation error:

Prisma schema loaded from prisma/schema.prisma

Datasource "db": SQLite database "prod.db" at "file:/usr/src/app/data/prod.db?connection_limit=1"

26 migrations found in prisma/migrations


Error: P3009

migrate found failed migrations in the target database, new migrations will not be applied. Read more about how to resolve migration issues in a production database: https://pris.ly/d/migrate-resolve

The `20231017150829_remove_expires_in` migration started at 2024-12-11 05:36:20.332 UTC failed

Running seed command `node prisma/seed.js` ...

roles are synced

PrismaClientKnownRequestError: 

Invalid `prisma.user.findMany()` invocation:

The column `main.user.hashedPassword` does not exist in the current database.

    at Mn.handleRequestError (/usr/src/app/node_modules/.pnpm/@prisma+client@6.0.1_prisma@6.0.1/node_modules/@prisma/client/runtime/library.js:121:7338)

    at Mn.handleAndLogRequestError (/usr/src/app/node_modules/.pnpm/@prisma+client@6.0.1_prisma@6.0.1/node_modules/@prisma/client/runtime/library.js:121:6663)

    at Mn.request (/usr/src/app/node_modules/.pnpm/@prisma+client@6.0.1_prisma@6.0.1/node_modules/@prisma/client/runtime/library.js:121:6370)

    at async l (/usr/src/app/node_modules/.pnpm/@prisma+client@6.0.1_prisma@6.0.1/node_modules/@prisma/client/runtime/library.js:130:9633)

    at async groups (file:///usr/src/app/prisma/seed.js:51:26)

    at async main (file:///usr/src/app/prisma/seed.js:189:5) {

  code: 'P2022',

**Comment by cmintey** [comment]
Not sure why the migration failed. I can't reproduce it using the docker-compose in the readme. Try deleting the prod.db file in your data folder and restart the container

**Comment by robajr** [comment]
Removing the .db was fine, the 26 migrations occurred successfully. Curious if the container image ships with a .db that can't migrate, or is otherwise invalid? Thanks for the quick support.

**Comment by cmintey** [comment]
It shouldn’t, but I will check the build. Thanks!
